# Step 1
Importing all necessary imports

In [14]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt

# Step 2
Reading data as dataframe

In [4]:
data = pd.read_csv("cinema.csv")
data.head(2)

,Unnamed: 0,Title,title_year,budget,Gross,actor_1_name,actor_2_name,actor_3_name,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,IMDb_rating,genre_1,genre_2,genre_3,Runtime,content_rating,Country
0,0,La La Land,2016,30000000,151101803,Ryan Gosling,Emma Stone,Amiée Conn,14000,19000.0,NaN,8.2,Comedy,Drama,Music,128,PG-13,USA
1,1,Zootopia,2016,150000000,341268248,Ginnifer Goodwin,Jason Bateman,Idris Elba,2800,28000.0,27000.0,8.1,Animation,Adventure,Comedy,108,PG,USA

In [5]:
data.columns

Index(['Unnamed: 0', 'Title', 'title_year', 'budget', 'Gross', 'actor_1_name',
       'actor_2_name', 'actor_3_name', 'actor_1_facebook_likes',
       'actor_2_facebook_likes', 'actor_3_facebook_likes', 'IMDb_rating',
       'genre_1', 'genre_2', 'genre_3', 'Runtime', 'content_rating',
       'Country'],
      dtype='object')

In [7]:
data.corr()

,Unnamed: 0,title_year,budget,Gross,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,IMDb_rating,Runtime
Unnamed: 0,1.000000,-0.265008,-0.682457,-0.423238,-0.255931,-0.403100,-0.413985,-0.185250,-0.259044
title_year,-0.265008,1.000000,0.047194,0.108930,0.004138,0.274125,0.191715,0.140239,0.031092
budget,-0.682457,0.047194,1.000000,0.760114,0.123067,0.051393,0.328815,0.225800,0.352666
Gross,-0.423238,0.108930,0.760114,1.000000,0.070104,0.060883,0.294711,0.270453,0.255991
actor_1_facebook_likes,-0.255931,0.004138,0.123067,0.070104,1.000000,0.381536,0.304237,0.296544,0.175864
actor_2_facebook_likes,-0.403100,0.274125,0.051393,0.060883,0.381536,1.000000,0.505427,0.209267,0.118421
actor_3_facebook_likes,-0.413985,0.191715,0.328815,0.294711,0.304237,0.505427,1.000000,0.185154,0.100897
IMDb_rating,-0.185250,0.140239,0.225800,0.270453,0.296544,0.209267,0.185154,1.000000,0.259959
Runtime,-0.259044,0.031092,0.352666,0.255991,0.175864,0.118421,0.100897,0.259959,1.000000

In [15]:
Gross_budget = data[["Gross", "budget"]]
plt.bar(Gross_budget)

TypeError: bar() missing 1 required positional argument: 'height'